### ISSUE TITLE
facedancer-host-enumeration

### ISSUE THREAD

**Issue by amado4884** [usb-tools/Facedancer#17]
Hello, thank you for your awesome work!

For the life of me I can't seem to get this working. I've tried it on two different computers, one Ubuntu, one Windows and the script always breaks here:

```
E:\USBStuff\Facedancer>facedancer-host-enumeration.py
Using GreatDancer Host backend.
Traceback (most recent call last):
  File "E:\USBStuff\Facedancer\facedancer-host-enumeration.py", line 9, in <module>
    u.initialize_device(assign_address=1, apply_configuration=1)
  File "E:\USBStuff\Facedancer\facedancer\core.py", line 374, in initialize_device
    self.apply_configuration(apply_configuration)
  File "E:\USBStuff\Facedancer\facedancer\core.py", line 451, in apply_configuration
    configuration = self.get_configuration_descriptor(index - 1)
  File "E:\USBStuff\Facedancer\facedancer\core.py", line 405, in get_configuration_descriptor
    descriptor = USBConfiguration.from_binary_descriptor(raw_descriptor)
  File "E:\USBStuff\Facedancer\facedancer\USBConfiguration.py", line 55, in from_binary_descriptor
    attributes, max_power = struct.unpack('<xBHBBBBB', data[0:length])
struct.error: unpack requires a bytes object of length 9
```
I'm using the GreatFET One, and I get the same error on both operating systems.
Just to try and figure out what's going on, I printed the output of the data variable just before line 55 in USBConfiguration.py and this was the value:
```
b'\t\x02"\x00\x01\x01\x00\x80'
```
I've tried changing the fmt string in line 55 to "<xBBBBBBB" instead of "<xBHBBBBB" but that just temporarily fixes the issue because then I get another error:
```
E:\USBStuff\Facedancer>facedancer-host-enumeration.py
Using GreatDancer Host backend.
Device initialized:
        Device is: Connected
        Device speed: Low speed
        Port is: Enabled
        Port power is: On
        Line state: J
Traceback (most recent call last):
  File "E:\USBStuff\Facedancer\facedancer-host-enumeration.py", line 25, in <module>
    print("Attached device: {}".format(u.get_device_descriptor()))
  File "E:\USBStuff\Facedancer\facedancer\core.py", line 391, in get_device_descriptor
    return USBDevice.from_binary_descriptor(raw_descriptor)
  File "E:\USBStuff\Facedancer\facedancer\USBDevice.py", line 98, in from_binary_descriptor
    data.extend([0] * padding_necessary)
AttributeError: 'bytes' object has no attribute 'extend'
```
I changed it back to the original "<xBHBBBBB" because I figure that there must be something wrong on my systems since no one else has had this issue. 
Any help would be greatly appreciated!

**Comment by ktemkin** [comment]
Sorry for the delayed response -- I've been at conferences for a lot of the past few weeks, and haven't had a chance to investigate this until now.

Looks like there was an issue with the convenience `initialize_device` method, which is meant to perform a default initialization as a USB host might -- it was missing a step that correctly determines the maximum packet size on EP0.

This resulted in it assuming a maximum packet size that was too large for the connected device -- in your case, assuming that packets would be 64B rather than your device's actual maximum packet size of 8B.

What one would normally expect to see would be two packets that convey the 9-byte configuration descriptor, with roughly the following layout:

```
[1 2 3 4 5 6 7 8] [9]
```

A USB device indicates that a data transfer has ended by sending a packet of less than maximum length. If the USB device were correctly configured to look for an 8-byte maximum packet size, it'd have read both packets, stopping when it received the second, single-byte packet, as it contains less than the maximum length of eight bytes.

If the host mistakenly is configured for a larger maximum packet size, then the same transfer goes very differently. Let's assume a maximum packet size of 64. When the host asks for the nine-byte device descriptor, the device still sends the same first packet...

```
[1 2 3 4 5 6 7 8]
```
... but to the host, this is recognized as a packet with _shorter than the maximum length_, as 8B < 64B. The host then believes the devices has finished speaking, and interprets this as the device sending back an eight-byte device descriptor. Oops!

This should be fixed in master:

https://github.com/usb-tools/Facedancer/commit/56f0d13a77bf93d8d322601956afc972c445a883

That commit has the device read the EP0 maximum packet size before issuing any further communications, which ensures that we have our max-packet-size set properly.

Can you try this and let me know if this makes things work for you? I'm confident in this solution enough to close the issue; but I'd be more than happy to re-open it if things are still broken for you. :)
